### ISSUE TITLE
Lowercase slugs break existing incoming external links

### ISSUE THREAD

**Issue by agarella** [narative/gatsby-theme-novela#336]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

Latest version breaks existing links to my website due to all the slugs being lowercased

### Version of Novela you are using
0.14.6

### Number of posts you have and which data source
* [x] Local
* [ ] Contentful

### Describe the bug

This change makes all slugs lowercase:

https://github.com/narative/gatsby-theme-novela/pull/326/files#diff-df88a2d045b58d91843cd68243927187R46

Unfortunately that breaks all links from external websites that point to links that were capitalized. If I try to override the default slug in the article with a capitalized version the actual slugs remain lowercase. The only workaround I see is fixing this is by redirecting the previous URLs that I had to these new lowercased ones, which is not ideal.

Ideally I would be able to override the slug with a capitalized one.

### To Reproduce
1. Upgrade to 0.14.6
2. Any external link pointing to existing capitalized slug URLs breaks

### Expected behavior
I expect to be able to work around this by explicitly setting the slug to what it originally was. I.e. the capitalized version. Unfortunately when I try that it gets lowercased as well.

**Comment by Ba2dones** [comment]
Fixed in #345. You can check it now.

**Comment by agarella** [comment]
Hi @Ba2dones thanks for your PR. Unfortunately while testing it locally in dev mode it's still broken for me. The default slug still seems to be lowercase and if I try to manually override the slug it remains lowercase.
